=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2026.05.26 04:29:06 =~=~=~=~=~=~=~=~=~=~=~=
show ri unning-conf
Building configuration...

Current configuration : 1078 bytes
!
version 12.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R2
!
boot-start-marker
boot-end-marker
!
!
no aaa new-model
memory-size iomem 5
no ip icmp rate-limit unreachable
!
!
ip cef
no ip domain lookup
no ip dhcp use vrf connected
ip dhcp excluded-address 192.168.1.1
 --More--         ip dhcp excluded-address 192.168.2.1
 --More--         !
 --More--         ip dhcp pool LAN1
 --More--            network 192.168.1.0 255.255.255.0
 --More--            default-router 192.168.1.1 
 --More--         !
 --More--         ip dhcp pool LAN2
 --More--            network 192.168.2.0 255.255.255.0
 --More--            default-router 192.168.2.1 
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         ip tcp synwait-time 5
 --More--         !
 --More--         !
 --More--         !
 --More--         interface FastEthernet0/0
 --More--          ip address 10.0.0.2 255.255.255.252
 --More--          duplex auto
 --More--          speed auto
 --More--         !
 --More--         !
 --More--         no ip http server
 --More--         ip forward-protocol nd
 --More--         ip route 192.168.1.0 255.255.255.0 10.0.0.1
 --More--         ip route 192.168.2.0 255.255.255.0 10.0.0.1
 --More--         !
 --More--         !
 --More--         !
 --More--         no cdp log mismatch duplex
 --More--         !
 --More--         !
 --More--         !
 --More--         control-plane
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         !
 --More--         line con 0
 --More--          exec-timeout 0 0
 --More--          privilege level 15
 --More--          logging synchronous
 --More--         line aux 0
 --More--          exec-timeout 0 0
 --More--          privilege level 15
 --More--          logging synchronous
 --More--         line vty 0 4
 --More--          login
 --More--         !
 --More--         !
 --More--         end
 --More--         
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#
R2#